Hw02 express
Anelliya/nodejs-homework-rest-api pull request #1
Opened 2021-05-16 07:28 UTC by Anelliya

adds the whole project

2021-05-17 19:36 UTC, SergeiKBB requested changes

2021-05-17 19:36 UTC, SergeiKBB commented on model/index.js
> +      const contactsList = JSON.parse(await fs.readFile(contactsPath));
почему не используешь функцию listContacts для получения списка контактов?

2021-05-17 19:36 UTC, SergeiKBB commented on routes/api/contacts.js
> +      return next(
зачем вызываешь некст и передаешь ему вызом `res.status(404).json({})`?

2021-05-21 03:59 UTC, Anelliya commented on model/index.js
> +      const contactsList = JSON.parse(await fs.readFile(contactsPath));
Исправила

2021-05-21 04:00 UTC, Anelliya commented on routes/api/contacts.js
> +      return next(
Исправила

2021-05-21 12:14 UTC, SergeiKBB requested changes

2021-05-21 12:14 UTC, SergeiKBB commented on model/index.js
> +      const contactsList = listContacts();
проверяла работоспособность? listContacts - это асинхрона функция из-за этого в contactsList запишется промис а не результат выполнения

2021-05-22 03:24 UTC, Anelliya commented on model/index.js
> +      const contactsList = listContacts();
Проверила и исправила

2021-05-22 20:07 UTC, SergeiKBB approved these changes

2021-05-23 03:42 UTC, merged